example_setting:
  default: true


promo_trigger_tags:
  type: list
  list_type: tag
  default: ""
  description: "Tags that trigger the promo button. The button will link to [wrap=TAG] content in the first post."

promo_button_icon:
  type: string
  default: "gift"
  description: "Enter a Font Awesome icon name without the 'fa-' prefix (e.g., 'gift', 'chevron-up', 'arrow-up')"

promo_wrap_accent:
  type: enum
  default: "tertiary"
  choices:
    - tertiary
    - success
    - love
    - danger
  description: "Accent color for promo containers (left border highlight)"

promo_wrap_spacing:
  type: enum
  default: "space-3"
  choices:
    - space-2
    - space-3
    - space-4
  description: "Padding size for promo containers"

promo_wrap_compact_mobile:
  type: bool
  default: true
  description: "Reduce promo container padding on mobile devices"



sticky_banner_text:
  type: string
  default: "See the promo"

sticky_banner_cookie_name:
  type: string
  default: "sticky_banner_dismissed_post"

sticky_banner_cookie_lifespan:
  type: integer
  default: 30
  min: 1
  max: 365

display_sticky_banner_mobile:
  type: bool
  default: true

display_sticky_banner_desktop:
  type: bool
  default: true
