example_setting:
  default: true


promo_trigger_tags:
  type: list
  list_type: tag
  default: ""
  description: "Tags that trigger the promo button. The button will link to [wrap=TAG] content in the first post."

promo_button_icon:
  type: string
  default: "gift"
  description: "Enter a Font Awesome icon name without the 'fa-' prefix (e.g., 'gift', 'chevron-up', 'arrow-up')"
